#!/bin/bash

set -x

export AUR=/aur
export BUILD=/home/tomegathericon/build


for f in $@;

do 

abs_path=$(find /var/abs/ -name $f | grep $f)

find /var/abs/ -name $f | grep $f

if [ $? -eq 0 ]; then

sudo rsync -arvhP $abs_path $BUILD

sudo chown -R tomegathericon:wheel $BUILD

cd $BUILD/$f

makepkg -si
	
#sudo pacman -S $f

else

cd $AUR

cower -d $f

cd $f

makepkg -si

fi

shift

done


