#!/bin/bash
set -x
packer_home=/git/packer
td_container_name=tomegathericon
td_image=411760385375.dkr.ecr.us-west-2.amazonaws.com/tomegathericon/nginx-via-packer
td_cpu=500
td_memory=500
containerport=80
td_name=tomegathericon
service_name=tomegathericon
cd $packer_home/docker
packer build nginx-via-packer-ecr
cd /git/rtl/aws-cli
sed -i s/td_container_name/$td_container_name/g create-task-definition
sed -i s{td_image{$td_image{g create-task-definition
sed -i s/td_cpu/$td_cpu/g create-task-definition
sed -i s/td_memory/$td_memory/g create-task-definition
sed -i s/containerport/$containerport/g create-task-definition
sed -i s/td_name/$td_name/g create-task-definition
sed -i s/service_name/$service_name/g create-service
sed -i s/td_name/$td_name/g create-service
aws ecs register-task-definition --cli-input-json file://create-task-definition
aws ecs create-service --cli-input-json file://create-service

